apiVersion: v1
kind: Service
metadata:
  name: smoke-cloud{{ .Values.application.suffix }}-service
spec:
  selector:
    app: smoke-cloud{{ .Values.application.suffix }}
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32002
  type: ExternalName
  externalName: 89.223.93.139